CREATE TABLE IF NOT EXISTS "users"(
ID TEXT, Name TEXT, Gender TEXT, Age TEXT,
 Birthdate TEXT, Address TEXT);
CREATE TABLE IF NOT EXISTS "stores"(
ID TEXT, Name TEXT, Type TEXT, Address TEXT);
CREATE TABLE IF NOT EXISTS "orders"(
ID TEXT, OrderAt DATETIME, StoreID TEXT, UserID TEXT);
CREATE TABLE IF NOT EXISTS "orderitems"(
ID TEXT, OrderID TEXT, ItemID TEXT);
CREATE TABLE IF NOT EXISTS "items"(
ID TEXT, Name TEXT, Type TEXT, UnitPrice TEXT);